# -*- coding: utf-8 -*-
"""Копия блокнота "utc_data.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QlGzXfyoneyJZdw6x3gW5HK0-o5smzYJ
"""

#@title Select UTC laboratories
lab1 = "Russian Federation - SU" #@param ['Argentina - AGGO', 'Argentina - INTI', 'Argentina - IGNA', 'Argentina - ONBA', 'Australia - AUS', 'Austria - BEV', 'Austria - TUG', 'Belarus - BY', 'Belgium - SMD', 'Belgium - ORB', 'Bosnia and Herzegovina - IMBH', 'Brazil - LRTE', 'Brazil - INXE', 'Brazil - ONRJ', 'Bulgaria - BIM', 'Canada - NRC', 'Chinese Taipei - TL', 'Colombia - INM', 'Costa Rica - ICE', 'Czech Republic - TP', 'Denmark - DFM', 'Egypt - NIS', 'Finland - MIKE', 'France - OP', 'France - CNES', 'Germany - IFAG', 'Germany - DTAG', 'Germany - DLR', 'Germany - PTB', 'Greece - EIM', 'Hong Kong (China) - SCL', 'Hong Kong (China) - HKO', 'Hungary - BFKH', 'India - NPLI', 'Indonesia - IDN', 'Ireland - NSAI', 'Israel - INPL', 'Italy - CAO', 'Italy - IT', 'Japan - NICT', 'Japan - NMIJ', 'Japan - NAO', 'Kazakhstan - KZ', 'Kenya - KEBS', 'Latvia - LV', 'Lithuania - LT', 'Luxembourg - LUX', 'Macedonia - BOM', 'Malaysia - NMLS', 'Mexico - CNM', 'Mongolia - MASM', 'Montenegro - MBM', 'New Zealand - MSL', 'Norway - JV', 'P.R. China - NIM', 'P.R. China - BIRM', 'P.R. China - JATC', 'P.R. China - NTSC', 'Panama - CNMP', 'Peru - INCP', 'Poland - AOS', 'Poland - PL', 'Portugal - IPQ', 'Rep. of Korea - KRIS', 'Romania - NIMB', 'Russian Federation - SU', 'Saudi Arabia - SASO', 'Saudi Arabia - MTC', 'Serbia - DMDM', 'Singapore - SG', 'Slovakia - SMU', 'Slovenia - SIQ', 'South Africa - ZA', 'Spain - ROA', 'Sri Lanka - SL', 'Sweden - SP', 'Switzerland - CH', 'Thailand - NIMT', 'The Netherlands - ESA', 'The Netherlands - VSL', 'The United Arab Emirates - UAE', 'Tunisia - DFNT', 'Türkiye - UME', 'Ukraine - UA', 'United Kingdom - NPL', 'United Kingdom - LDS', 'United States of America - APL', 'United States of America - NRL', 'United States of America - USNO', 'United States of America - NIST', 'Vietnam - VMI']
lab2 = "United States of America - USNO" #@param ['None', 'Argentina - AGGO', 'Argentina - INTI', 'Argentina - IGNA', 'Argentina - ONBA', 'Australia - AUS', 'Austria - BEV', 'Austria - TUG', 'Belarus - BY', 'Belgium - SMD', 'Belgium - ORB', 'Bosnia and Herzegovina - IMBH', 'Brazil - LRTE', 'Brazil - INXE', 'Brazil - ONRJ', 'Bulgaria - BIM', 'Canada - NRC', 'Chinese Taipei - TL', 'Colombia - INM', 'Costa Rica - ICE', 'Czech Republic - TP', 'Denmark - DFM', 'Egypt - NIS', 'Finland - MIKE', 'France - OP', 'France - CNES', 'Germany - IFAG', 'Germany - DTAG', 'Germany - DLR', 'Germany - PTB', 'Greece - EIM', 'Hong Kong (China) - SCL', 'Hong Kong (China) - HKO', 'Hungary - BFKH', 'India - NPLI', 'Indonesia - IDN', 'Ireland - NSAI', 'Israel - INPL', 'Italy - CAO', 'Italy - IT', 'Japan - NICT', 'Japan - NMIJ', 'Japan - NAO', 'Kazakhstan - KZ', 'Kenya - KEBS', 'Latvia - LV', 'Lithuania - LT', 'Luxembourg - LUX', 'Macedonia - BOM', 'Malaysia - NMLS', 'Mexico - CNM', 'Mongolia - MASM', 'Montenegro - MBM', 'New Zealand - MSL', 'Norway - JV', 'P.R. China - NIM', 'P.R. China - BIRM', 'P.R. China - JATC', 'P.R. China - NTSC', 'Panama - CNMP', 'Peru - INCP', 'Poland - AOS', 'Poland - PL', 'Portugal - IPQ', 'Rep. of Korea - KRIS', 'Romania - NIMB', 'Russian Federation - SU', 'Saudi Arabia - SASO', 'Saudi Arabia - MTC', 'Serbia - DMDM', 'Singapore - SG', 'Slovakia - SMU', 'Slovenia - SIQ', 'South Africa - ZA', 'Spain - ROA', 'Sri Lanka - SL', 'Sweden - SP', 'Switzerland - CH', 'Thailand - NIMT', 'The Netherlands - ESA', 'The Netherlands - VSL', 'The United Arab Emirates - UAE', 'Tunisia - DFNT', 'Türkiye - UME', 'Ukraine - UA', 'United Kingdom - NPL', 'United Kingdom - LDS', 'United States of America - APL', 'United States of America - NRL', 'United States of America - USNO', 'United States of America - NIST', 'Vietnam - VMI']
lab3 = "Mexico - CNM" #@param ['None', 'Argentina - AGGO', 'Argentina - INTI', 'Argentina - IGNA', 'Argentina - ONBA', 'Australia - AUS', 'Austria - BEV', 'Austria - TUG', 'Belarus - BY', 'Belgium - SMD', 'Belgium - ORB', 'Bosnia and Herzegovina - IMBH', 'Brazil - LRTE', 'Brazil - INXE', 'Brazil - ONRJ', 'Bulgaria - BIM', 'Canada - NRC', 'Chinese Taipei - TL', 'Colombia - INM', 'Costa Rica - ICE', 'Czech Republic - TP', 'Denmark - DFM', 'Egypt - NIS', 'Finland - MIKE', 'France - OP', 'France - CNES', 'Germany - IFAG', 'Germany - DTAG', 'Germany - DLR', 'Germany - PTB', 'Greece - EIM', 'Hong Kong (China) - SCL', 'Hong Kong (China) - HKO', 'Hungary - BFKH', 'India - NPLI', 'Indonesia - IDN', 'Ireland - NSAI', 'Israel - INPL', 'Italy - CAO', 'Italy - IT', 'Japan - NICT', 'Japan - NMIJ', 'Japan - NAO', 'Kazakhstan - KZ', 'Kenya - KEBS', 'Latvia - LV', 'Lithuania - LT', 'Luxembourg - LUX', 'Macedonia - BOM', 'Malaysia - NMLS', 'Mexico - CNM', 'Mongolia - MASM', 'Montenegro - MBM', 'New Zealand - MSL', 'Norway - JV', 'P.R. China - NIM', 'P.R. China - BIRM', 'P.R. China - JATC', 'P.R. China - NTSC', 'Panama - CNMP', 'Peru - INCP', 'Poland - AOS', 'Poland - PL', 'Portugal - IPQ', 'Rep. of Korea - KRIS', 'Romania - NIMB', 'Russian Federation - SU', 'Saudi Arabia - SASO', 'Saudi Arabia - MTC', 'Serbia - DMDM', 'Singapore - SG', 'Slovakia - SMU', 'Slovenia - SIQ', 'South Africa - ZA', 'Spain - ROA', 'Sri Lanka - SL', 'Sweden - SP', 'Switzerland - CH', 'Thailand - NIMT', 'The Netherlands - ESA', 'The Netherlands - VSL', 'The United Arab Emirates - UAE', 'Tunisia - DFNT', 'Türkiye - UME', 'Ukraine - UA', 'United Kingdom - NPL', 'United Kingdom - LDS', 'United States of America - APL', 'United States of America - NRL', 'United States of America - USNO', 'United States of America - NIST', 'Vietnam - VMI']
lab4 = "Germany - PTB" #@param ['None', 'Argentina - AGGO', 'Argentina - INTI', 'Argentina - IGNA', 'Argentina - ONBA', 'Australia - AUS', 'Austria - BEV', 'Austria - TUG', 'Belarus - BY', 'Belgium - SMD', 'Belgium - ORB', 'Bosnia and Herzegovina - IMBH', 'Brazil - LRTE', 'Brazil - INXE', 'Brazil - ONRJ', 'Bulgaria - BIM', 'Canada - NRC', 'Chinese Taipei - TL', 'Colombia - INM', 'Costa Rica - ICE', 'Czech Republic - TP', 'Denmark - DFM', 'Egypt - NIS', 'Finland - MIKE', 'France - OP', 'France - CNES', 'Germany - IFAG', 'Germany - DTAG', 'Germany - DLR', 'Germany - PTB', 'Greece - EIM', 'Hong Kong (China) - SCL', 'Hong Kong (China) - HKO', 'Hungary - BFKH', 'India - NPLI', 'Indonesia - IDN', 'Ireland - NSAI', 'Israel - INPL', 'Italy - CAO', 'Italy - IT', 'Japan - NICT', 'Japan - NMIJ', 'Japan - NAO', 'Kazakhstan - KZ', 'Kenya - KEBS', 'Latvia - LV', 'Lithuania - LT', 'Luxembourg - LUX', 'Macedonia - BOM', 'Malaysia - NMLS', 'Mexico - CNM', 'Mongolia - MASM', 'Montenegro - MBM', 'New Zealand - MSL', 'Norway - JV', 'P.R. China - NIM', 'P.R. China - BIRM', 'P.R. China - JATC', 'P.R. China - NTSC', 'Panama - CNMP', 'Peru - INCP', 'Poland - AOS', 'Poland - PL', 'Portugal - IPQ', 'Rep. of Korea - KRIS', 'Romania - NIMB', 'Russian Federation - SU', 'Saudi Arabia - SASO', 'Saudi Arabia - MTC', 'Serbia - DMDM', 'Singapore - SG', 'Slovakia - SMU', 'Slovenia - SIQ', 'South Africa - ZA', 'Spain - ROA', 'Sri Lanka - SL', 'Sweden - SP', 'Switzerland - CH', 'Thailand - NIMT', 'The Netherlands - ESA', 'The Netherlands - VSL', 'The United Arab Emirates - UAE', 'Tunisia - DFNT', 'Türkiye - UME', 'Ukraine - UA', 'United Kingdom - NPL', 'United Kingdom - LDS', 'United States of America - APL', 'United States of America - NRL', 'United States of America - USNO', 'United States of America - NIST', 'Vietnam - VMI']
lab5 = "Kazakhstan - KZ" #@param ['None', 'Argentina - AGGO', 'Argentina - INTI', 'Argentina - IGNA', 'Argentina - ONBA', 'Australia - AUS', 'Austria - BEV', 'Austria - TUG', 'Belarus - BY', 'Belgium - SMD', 'Belgium - ORB', 'Bosnia and Herzegovina - IMBH', 'Brazil - LRTE', 'Brazil - INXE', 'Brazil - ONRJ', 'Bulgaria - BIM', 'Canada - NRC', 'Chinese Taipei - TL', 'Colombia - INM', 'Costa Rica - ICE', 'Czech Republic - TP', 'Denmark - DFM', 'Egypt - NIS', 'Finland - MIKE', 'France - OP', 'France - CNES', 'Germany - IFAG', 'Germany - DTAG', 'Germany - DLR', 'Germany - PTB', 'Greece - EIM', 'Hong Kong (China) - SCL', 'Hong Kong (China) - HKO', 'Hungary - BFKH', 'India - NPLI', 'Indonesia - IDN', 'Ireland - NSAI', 'Israel - INPL', 'Italy - CAO', 'Italy - IT', 'Japan - NICT', 'Japan - NMIJ', 'Japan - NAO', 'Kazakhstan - KZ', 'Kenya - KEBS', 'Latvia - LV', 'Lithuania - LT', 'Luxembourg - LUX', 'Macedonia - BOM', 'Malaysia - NMLS', 'Mexico - CNM', 'Mongolia - MASM', 'Montenegro - MBM', 'New Zealand - MSL', 'Norway - JV', 'P.R. China - NIM', 'P.R. China - BIRM', 'P.R. China - JATC', 'P.R. China - NTSC', 'Panama - CNMP', 'Peru - INCP', 'Poland - AOS', 'Poland - PL', 'Portugal - IPQ', 'Rep. of Korea - KRIS', 'Romania - NIMB', 'Russian Federation - SU', 'Saudi Arabia - SASO', 'Saudi Arabia - MTC', 'Serbia - DMDM', 'Singapore - SG', 'Slovakia - SMU', 'Slovenia - SIQ', 'South Africa - ZA', 'Spain - ROA', 'Sri Lanka - SL', 'Sweden - SP', 'Switzerland - CH', 'Thailand - NIMT', 'The Netherlands - ESA', 'The Netherlands - VSL', 'The United Arab Emirates - UAE', 'Tunisia - DFNT', 'Türkiye - UME', 'Ukraine - UA', 'United Kingdom - NPL', 'United Kingdom - LDS', 'United States of America - APL', 'United States of America - NRL', 'United States of America - USNO', 'United States of America - NIST', 'Vietnam - VMI']
lablist = [lab1]
if lab2 != 'None':
  lablist.append(lab2)
if lab3 != 'None':
  lablist.append(lab3)
if lab4 != 'None':
  lablist.append(lab4)
if lab5 != 'None':
  lablist.append(lab5)

from astropy.time import Time
from datetime import datetime
#@title Select dates
date_start = '2022-01-01' #@param {type:"date"}
date_end = '2022-09-01' #@param {type:"date"}
mjd_start = int(Time(datetime.fromisoformat(date_start)).mjd)
mjd_end = int(Time(datetime.fromisoformat(date_end)).mjd)
print("MJD start = ", mjd_start)
print("MJD end = ", mjd_end)

#@title UTC or UTCr?
utc = "utc" #@param ['utc', 'utcr']

import requests
import pandas as pd
datalist = []
for lab in lablist:
  lab_ref = lab.split(' - ')[1]
  rqst_str = "https://webtai.bipm.org/api/v0.1/get-data.html?scale="+utc+"&lab="+lab_ref+"&mjd1="+str(mjd_start)+"&mjd2="+str(mjd_end)
  r = requests.get(rqst_str)
  data = (r.json())['data'][0]  
  listdt = Time(data['x'], format='mjd', scale='utc').datetime
  dstrlist = []
  for t in listdt:
    dstrlist.append(t.strftime('%Y-%m-%d'))
  df = pd.DataFrame({'Date': dstrlist, 'Offset': data['y']})
  datalist.append([df, lab_ref])

import plotly.graph_objects as go
fig = go.Figure()
for data in datalist:
  fig.add_trace(go.Scatter(x=data[0].Date, y=data[0].Offset, name=data[1], mode='markers+lines'))
fig.update_layout(legend_orientation="h",
                  legend=dict(x=.5, xanchor="center"),
                  title="UTC - UTC(k) time offset",                  
                  yaxis_title="Offset, ns")
fig.show()